### ISSUE TITLE
Why are Intl.PluralRules packaged with this build?

### ISSUE THREAD

**Issue by andrejpavlovic** [catamphetamine/relative-time-format#5] opened 2019-09-05 18:09 UTC
Why not allow users to polyfill the Intl.PluralRules functionality themselves? It would be more size efficient if this library only acted as a polyfill for Intl.RelativeTimeFormat instead of trying to polyfill other parts of the Intl library as well. Maybe at least offer a way to include Intl.RelativeTimeFormat without other polyfills?

**Comment by catamphetamine** [comment] 2019-09-05 18:52
Closing as duplicate of https://github.com/catamphetamine/javascript-time-ago/issues/21

**Closed as completed by catamphetamine** 2019-09-05 18:52 UTC
